# Generated by Django 5.1.3 on 2024-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_session_qr_code_student_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp',
        ),
        migrations.AddField(
            model_name='student',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
