# Generated by Django 5.1.3 on 2024-11-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_student_otp_student_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
