# Generated by Django 5.1.3 on 2024-11-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_student_device_id_student_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
