# Generated by Django 5.1.3 on 2024-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_session_end_time_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
