# Generated by Django 5.1.3 on 2024-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_session_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
