# Generated by Django 5.1.3 on 2024-11-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_session_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
